### ISSUE TITLE
Gamepad virtual mouse needs to be edited

### ISSUE THREAD

**Issue by JammySquirrel** [CoderDojo-Ennis/HybernRPG#94]
I spoke to Quinn about this before leaving his house today. The virtual mouse poses a problem when the player is off centre, both for the limb selection wheel, and for aiming with the grappling hook. Needs to constantly have the centre of the player's torso as the mouses origin or something.

**Comment by QuinnPainter** [comment]
Should be fixed

**Comment by JammySquirrel** [comment]
Nope, virtual mouse still not working for me. The problem occurs while jumping. If you use the UI in midair, then you can't select all the options available.

**Comment by QuinnPainter** [comment]
Try it again. somehow my change got reverted
